username = input('Введите имя: ')
title = input('Заголовок: ')
title_1 = input('Основные темы: ')
title_2 = input('Номер этапа: ')
title_3 = input('Рекомендации для чтения: ')
list = []
list.append(title_1)
list.append(title_2)
list.append(title_3)
content = input('Описание: ')
status = input ('Состояние задачи: ')
create_date = input('Дата начала д.м.г: ')
issue_date = input('Дата окончания: д.м.г: ')

print(f'Имя: {username}.')
print(f'Заголовок: {title}.')
print(list)
print(f'Описание: {content}.')
print(f'Состояние задачи: {status}.')
print(f'Дата начала: {create_date[0:6]}')
print(f'Дата окончание: {issue_date[0:6]}')